// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBiY0_2s9d20BOdlqMdCMuH3h0WlYapbV4',
    appId: '1:825331287625:web:9c0f44d5e32d8ff715a198',
    messagingSenderId: '825331287625',
    projectId: 'test-paiecash-qr',
    authDomain: 'test-paiecash-qr.firebaseapp.com',
    storageBucket: 'test-paiecash-qr.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3SeY0wD3IJMm3YdmvTYzz7r2Im_N1CYw',
    appId: '1:825331287625:android:c9ce1cc0d400d4e615a198',
    messagingSenderId: '825331287625',
    projectId: 'test-paiecash-qr',
    storageBucket: 'test-paiecash-qr.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBFSd6LDqZFJfYZIb_oeLo54g5V9QCY2aY',
    appId: '1:825331287625:ios:0f1e0bb3ed50607015a198',
    messagingSenderId: '825331287625',
    projectId: 'test-paiecash-qr',
    storageBucket: 'test-paiecash-qr.appspot.com',
    iosClientId: '825331287625-n8i9igdcr6ic52n25iq0bop74lr7dgpb.apps.googleusercontent.com',
    iosBundleId: 'com.example.testPaiecash',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBFSd6LDqZFJfYZIb_oeLo54g5V9QCY2aY',
    appId: '1:825331287625:ios:eb787ebce81081f615a198',
    messagingSenderId: '825331287625',
    projectId: 'test-paiecash-qr',
    storageBucket: 'test-paiecash-qr.appspot.com',
    iosClientId: '825331287625-qt2dfvl2ba9o76hotv4ejhha8jvad5g4.apps.googleusercontent.com',
    iosBundleId: 'com.example.testPaiecash.RunnerTests',
  );
}
